services:
  node:
    image: node:20.16.0
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn encore dev-server --hot --host 0.0.0.0"
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/web:/usr/src/app:cached
